project:
  type: website

website:
  title: "IEW"
  
  page-footer: "Made using Quarto"

  search: 
    location: navbar
    type: textbox
  
  navbar:
    background: light
    collapse-below: lg
    search: true
    left:
    - href: index.qmd
      text: Home
    - href: IEWBrazil.qmd
      text: IEW Brazil

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
  

theme:
  light: flatly
  dark: darkly



