---
title: "Program"
---

### Monday (April 8)

17:00 Welcome reception

------------------------------------------------------------------------

### Tuesday (April 9)

8:00 Check in and tagging\
\
8:15 Opening remarks and welcome from SBF and ISPP representatives\
\
8:30 Keynote talk\
Some reflections on plant disease epidemiology since the first international workshop - Prof. Laurence Madden (The Ohio State University)\
\
9:30 **Thematic session 1 -** Artificial Intelligence and Remote Sensing in Plant Disease Epidemiology\
S1: Modernizing Plant Disease Monitoring: Integrating UAV and Ground-Based Imaging in Epidemiological Research - Christian Cruz (Purdue University)

S2: Global risk of Fusarium wilt mapped by remote sensing and aerosol transport modeling in a changing climate - Rocío Madrid (Cornell University)\
\
10:30 Coffee Break + group photo

11:00 **Oral session 1** (4 talks 10 min + 5 min discussion)

|             |                                                                                                                                                                    |
|-----------------|-------------------------------------------------------|
| Zhanhong Ma | The Application of Remote Sensing in Plant Disease Monitoring                                                                                                      |
| Ramirez-Gil | Development of digital platforms for data management and analysis for evidence-based decision-making of plant epidemics                                            |
| Melloy      | Utilising an application programming interface (API) for delivering spatial risk of blackspot to growers through commercial third-party farm management platforms. |
| Etherton    | Disaster plant pathology: smart solutions for natural and human-driven cataclysms threatening global plant health                                                  |

12:00 Lunch

13:30 **Thematic session 2** - Plant Disease Surveillance and Monitoring\
S1: Surveillance in systems with vectored diseases: gathering information to inform intervention - Neil McRoberts (University of California, Davis)

S2: Assessment of outbreak management plans: surveillance and control strategies for Xylella fastidiosa in the EU -Antonio Vicent (Institut Valencià d'Investigacions Agràries)

S3: What explains growers' fungicide use and management: From monitoring to causal inference - David Gent (Oregon State University)

15:00 **Oral session 2** (4 talks 10 min + 5 min discussion)

|               |                                                                                                                                                                           |
|-------------------|-----------------------------------------------------|
| Combes        | Examining the effect of ash dieback disease on the spread and detection of Emerald ash borer beetle in the UK                                                             |
| Borba         | Colletotrichum species infecting apples in Mid-Atlantic United States: identification, infection sources, geographical distribution, ecology and spore trapping with qPCR |
| von Tiedemann | Role of seed infection for the near and far distance spread of wheat blast caused by Magnaporthe oryzae pathotype Triticum                                                |
| Inoue-Nagata  | Enhancing geminivirus detection in plants: unveiling hidden threats with a cost-efficient RCA-RFLP method                                                                 |

16:00 Coffee break

16:20 **Oral session 3** (4 talks 10 min + 5 min discussion)

|          |                                                                                                                                      |
|------------------|------------------------------------------------------|
| Rothmann | Sorghum disease surveillance to understand South African producer perceptions and inform disease management and industry needs.      |
| Lopes    | Variation in the potential of diseased citrus trees in backyard as sources of Candidatus Liberibacter asiaticus to commercial groves |
| Sulá     | Global host-pathogen infection networks in major terrestrial agroecosystems                                                          |
| Canale   | Natural infectivity of the corn leafhopper, Dalbulus maidis, with the Corn Stunting Complex pathogens in Santa Catarina, Brazil      |

17:20 Poster viewing

19:30 Cocktail dinner at the Interlludium Hotel

------------------------------------------------------------------------

### Wednesday (April 10)

8:00 **Thematic session 3 -** Plant Disease Modeling and Forecasting\
S1: Pathogen process models: versatile tools for disease risk prediction - Robert Beresford (Plant and Food Research)

S2: Disease models for decision-making in crop protection - Irene Salotti (University of Sacro Cuori)

S3: Economic analysis of plant disease epidemics across multiple fields: estimating the economic cost of pathogen adaptation to control measures -Alexey Mikaberidze (University of Reading)

9:30 **Oral session 4** (4 talks 10 min + 5 min discussion)

|         |                                                                                                                                        |
|------------------|------------------------------------------------------|
| Jelev   | A model to predict spore maturation of Blumeriella jaapii in cherry                                                                    |
| Garnica | Novel Weather Variables Associated with Epidemics of Stagonospora Nodorum Blotch of Winter Wheat                                       |
| Smith   | Predicting Tar Spot of Corn in the U.S. -- Developing the Infrastructure for Corn Disease Modeling                                     |
| Acuna   | Using Environmental Variables for the Development of Logistic Regressions to Predict Frogeye Leaf Spot in Soybean in the United States |

10:30 - Coffee break

10:50 - **Oral session 5** (4 talks 10 min+5 discussion)

|          |                                                                                                                                                            |
|------------------|------------------------------------------------------|
| Cerbaro  | Influence of the El Niño Southern Oscillation on the risk of Botrytis fruit rot occurrence in Florida                                                      |
| Falla    | A mathematical model centred on aphid vector feeding behaviour has implications for plant host manipulation by non-persistently transmitted viruses        |
| Ferreira | Mitigating the Impact of Drought and Wheat Blast on Rainfed Wheat Production in the Brazilian Cerrado based on the selection of sowing dates and varieties |
| Rosace   | Spatial modelling of hotspots for plant pests introductions in the EU using regionalized data                                                              |

\
12:00 Lunch

13:30 **Thematic session 4 -** Climate Change and Plant Disease Epidemiology\
S1: Adapting global plant health management to global change: Opportunities for contributions from epidemiology -Karen Garret (University of Florida)

S2: Adam Sparks (Curtin University) 

15:00 **Oral session 6** (4 talks 10 min + 5 min discussion)

|               |                                                                                                                                                                                   |
|------------------|------------------------------------------------------|
| Chedjou       | Combining masculinizing resistance, rotation and biocontrol to achieve durable suppression of the potato pale cyst nematode: a model                                              |
| Gongora-Canul | Comparative Epidemiology of Tar Spot as an Endemic and Emerging Disease in the Americas                                                                                           |
| asalf         | Effect of cover crops and green manuring on sclerotinia white rot disease development and yield in carrot                                                                         |
| Helps         | What happens to durability of disease control in fields of growers who run a resistance management programme when neighbours use only one component of the resistance management? |

16:00 Coffee break\
16:20 Poster viewing

19:30 Dinner at Rafain Churrascaria Show

------------------------------------------------------------------------

### Thursday (April 11)

8:00 Tour Iguassu Falls

14:00 **Thematic session 5 -** Pathogen Evolution and Fungicide Resistance Management\
S1: Sidney Everhart (University of Connecticut)\
S2: Nik Cunniffe (University of Cambridge)\
S3: Managing fungicide resistance in Botrytis - Arne Stensvand (NIBIO)

15:45 Coffee break

16:15 **Oral session 7** (4 talks 10 min + 5 min discussion)

|               |                                                                                                                                                                                          |
|------------------|------------------------------------------------------|
| Paredes       | Analysis of the field-scale spatial pattern of peanut smut in Argentina                                                                                                                  |
| Thomas-Sharma | One brick at a time: Building on epidemiological insights for improved management of Cercospora leaf blight on soybean in the mid-South.                                                 |
| Philion       | Combining foliar deposit distribution and dose-response curve data to predict fungicide efficacy against scab in apple orchards, and practical implementation in the AOS43 dosing system |
| Gadoury       | A review of pathogen biology, ecology, epidemiology, and the use of germicidal ultraviolet light to suppress plant pathogens                                                             |

19:30 Dinner at 277 Craft Beer

------------------------------------------------------------------------

### Friday (April 12)

8:30 **Thematic session 6 -** Epidemiology-based management strategies\
S1: Epidemiology- based management of vegetable diseases - Mary Ruth McDonald (University of Guelph)

S2: Exploring Causal Relationships to Improve the Development of Production and Management Scenarios - Paul Esker (Penn State University)

S3: Epidemiology-based management strategies for citrus Huanglongbing - Renato Bassanezi (Fundecitrus)

10:45 Coffee break

11:00 Concluding remarks and planning for IEW14 
